name: Deploy Redirect to GitHub Pages

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Git Configuration
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Set up Python 3.11
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install AWS CLI
        run: |
          pip install awscli awscli-local

      - name: Run Ephemeral Script and Capture Output
        run: |
          pip3 install localstack
          bash bin/ephemeral.sh 2>&1 | tee output.log

          OUTPUT=$(cat output.log)
          NEW_URL=$(echo "$OUTPUT" | grep -Eo 'https://ls-[^ ]+')
          
          if [ -z "$NEW_URL" ]; then
            echo "Error: Failed to extract URL from script output."
            exit 1
          fi

          NEW_URL="${NEW_URL}#"
          echo "Extracted URL: $NEW_URL"
          echo "NEW_URL=$NEW_URL" >> $GITHUB_ENV
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
